/**
 * Browser-side Terraform HCL generator.
 *
 * Given the `ArgResource[]` already in the SPA, produce a complete file tree
 * (Map<path, content>) that mirrors what the PowerShell module would emit:
 *
 *   README.md
 *   .gitignore
 *   backend.tf.example
 *   docs/coverage.md
 *   infra/<rg>/
 *     main.tf
 *     provider.tf
 *     terraform.tf
 *     variables.tf
 *     terraform.tfvars.example
 *     outputs.tf
 *     README.md
 *
 * **Honesty**: this is a PREVIEW. The PowerShell module + `aztfexport`
 * remains the gold standard. The in-browser generator covers the ~15 most
 * common resource types in dev/test estates; for everything else it emits
 * an honest commented stub (`# TODO: ...`) plus a `moved` block hint so
 * users see exactly what is missing.
 */

import type { ArgResource } from '@/api/arm';

export interface GeneratedFile {
  path: string;
  content: string;
  language: 'hcl' | 'markdown' | 'json' | 'text';
}

export interface GenerateOptions {
  subscriptionId: string;
  subscriptionName?: string;
  resourceGroup?: string;
  resources: ArgResource[];
  generatorVersion?: string;
}

interface RenderContext {
  /** Map azure resource id (lowercased) → tf address ("type.name"). */
  idMap: Map<string, string>;
  /** Resource we are currently rendering. */
  resource: ArgResource;
}

interface RenderResult {
  /** The HCL block. Empty string when type is intentionally skipped. */
  hcl: string;
  /** Optional tf type for the outputs.tf entry (e.g. "azurerm_storage_account"). */
  tfType?: string;
  /** Optional tf name (e.g. "stcontoso"). */
  tfName?: string;
}

const HEADER_NOTICE = `# ─────────────────────────────────────────────────────────────────────────────
# Generated by azure-estate-exporter (web preview).
# This is a BASELINE. The PowerShell module + aztfexport remain the production
# path because they import resources into state so terraform plan shows
# "No changes". See README.md at the repo root.
# ─────────────────────────────────────────────────────────────────────────────
`;

// ────────────────────────────────────────────────────────────────────────────
// Utilities
// ────────────────────────────────────────────────────────────────────────────

/** Sanitize a name to fit Terraform identifier rules (`[a-z_][a-z0-9_-]*`). */
export function sanitizeName(raw: string): string {
  let s = raw.toLowerCase().replace(/[^a-z0-9_-]+/g, '_').replace(/^_+|_+$/g, '');
  if (!s) s = 'res';
  if (/^[0-9]/.test(s)) s = `r_${s}`;
  return s;
}

function quote(v: unknown): string {
  if (v === null || v === undefined) return '""';
  return JSON.stringify(String(v));
}

/** Defensive cast — returns `value` if it`s an array, otherwise an empty array. */
function asArray<T>(v: unknown): T[] {
  return Array.isArray(v) ? (v as T[]) : [];
}

/** Defensive cast — returns `value` if it`s a plain object, otherwise `{}`. */
function asObj(v: unknown): Record<string, unknown> {
  return v && typeof v === 'object' && !Array.isArray(v) ? (v as Record<string, unknown>) : {};
}

function tagsBlock(r: ArgResource): string {
  if (!r.tags || Object.keys(r.tags).length === 0) return '';
  const lines = Object.entries(r.tags).map(([k, v]) => `  ${quote(k)} = ${quote(v)}`);
  return `\n  tags = {\n${lines.join('\n')}\n  }`;
}

/** Build the `idMap` so renderers can refer to other resources via tf address. */
function buildIdMap(resources: ArgResource[]): Map<string, string> {
  const m = new Map<string, string>();
  // Always include the synthetic RG block.
  const seenRg = new Set<string>();
  for (const r of resources) {
    seenRg.add(r.resourceGroup.toLowerCase());
  }
  for (const rg of seenRg) {
    const rgId =
      `/subscriptions/${resources[0]?.subscriptionId ?? '<sub>'}/resourceGroups/${rg}`.toLowerCase();
    m.set(rgId, `azurerm_resource_group.${sanitizeName(rg)}`);
  }
  for (const r of resources) {
    const tfType = TF_TYPE_OF[r.type.toLowerCase()];
    if (tfType) {
      // For subnets the resource name is "vnet/subnet" but the block name is
      // just the subnet leaf, so the idMap must use the leaf too.
      const isSubnet = r.type.toLowerCase() === 'microsoft.network/virtualnetworks/subnets';
      const blockName = isSubnet ? (r.name.split('/').pop() ?? r.name) : r.name;
      m.set(r.id.toLowerCase(), `${tfType}.${sanitizeName(blockName)}`);
    }
  }
  return m;
}

/**
 * Resolve a hardcoded ARM id to a Terraform reference *if* the target is in
 * scope. Falls back to a JSON-quoted literal so the user can fix it manually.
 */
function refOrLiteral(armId: string, ctx: RenderContext, suffix = '.id'): string {
  const ref = ctx.idMap.get(armId.toLowerCase());
  if (ref) return `${ref}${suffix}`;
  return quote(armId);
}

// ────────────────────────────────────────────────────────────────────────────
// Map ARM type → Terraform resource type
// ────────────────────────────────────────────────────────────────────────────

const TF_TYPE_OF: Record<string, string> = {
  'microsoft.resources/resourcegroups': 'azurerm_resource_group',
  'microsoft.storage/storageaccounts': 'azurerm_storage_account',
  'microsoft.network/virtualnetworks': 'azurerm_virtual_network',
  'microsoft.network/virtualnetworks/subnets': 'azurerm_subnet',
  'microsoft.network/networkinterfaces': 'azurerm_network_interface',
  'microsoft.network/networksecuritygroups': 'azurerm_network_security_group',
  'microsoft.network/publicipaddresses': 'azurerm_public_ip',
  'microsoft.network/routetables': 'azurerm_route_table',
  'microsoft.compute/virtualmachines': 'azurerm_linux_virtual_machine', // adjusted by renderer for Windows
  'microsoft.compute/disks': 'azurerm_managed_disk',
  'microsoft.keyvault/vaults': 'azurerm_key_vault',
  'microsoft.web/serverfarms': 'azurerm_service_plan',
  'microsoft.web/sites': 'azurerm_linux_web_app', // adjusted for Windows
  'microsoft.operationalinsights/workspaces': 'azurerm_log_analytics_workspace',
  'microsoft.insights/components': 'azurerm_application_insights',
};

// ────────────────────────────────────────────────────────────────────────────
// Renderers
// ────────────────────────────────────────────────────────────────────────────

function renderResourceGroup(rgName: string, location: string, tags?: Record<string, string>): string {
  const tagsHcl =
    tags && Object.keys(tags).length
      ? `\n  tags = {\n${Object.entries(tags)
          .map(([k, v]) => `    ${quote(k)} = ${quote(v)}`)
          .join('\n')}\n  }`
      : '';
  return `resource "azurerm_resource_group" "${sanitizeName(rgName)}" {
  name     = ${quote(rgName)}
  location = ${quote(location)}${tagsHcl}
}`;
}

function renderStorageAccount(r: ArgResource): RenderResult {
  const p = (r.properties ?? {}) as Record<string, unknown>;
  const sku = (r.sku?.name ?? 'Standard_LRS').split('_');
  const tier = sku[0] ?? 'Standard';
  const repl = sku[1] ?? 'LRS';
  const tfName = sanitizeName(r.name);
  const hcl = `resource "azurerm_storage_account" "${tfName}" {
  name                     = ${quote(r.name)}
  resource_group_name      = azurerm_resource_group.${sanitizeName(r.resourceGroup)}.name
  location                 = ${quote(r.location)}
  account_tier             = ${quote(tier)}
  account_replication_type = ${quote(repl)}
  account_kind             = ${quote(r.kind ?? 'StorageV2')}
  min_tls_version          = ${quote(p.minimumTlsVersion ?? 'TLS1_2')}
  https_traffic_only_enabled = ${p.supportsHttpsTrafficOnly === false ? 'false' : 'true'}
  allow_nested_items_to_be_public = ${p.allowBlobPublicAccess === true ? 'true' : 'false'}
  public_network_access_enabled   = ${p.publicNetworkAccess === 'Disabled' ? 'false' : 'true'}${tagsBlock(r)}
}`;
  return { hcl, tfType: 'azurerm_storage_account', tfName };
}

function renderVirtualNetwork(r: ArgResource, ctx: RenderContext): RenderResult {
  const p = asObj(r.properties);
  const addrSpace = asArray<string>(asObj(p.addressSpace).addressPrefixes);
  const prefixes = addrSpace.length ? addrSpace : ['10.0.0.0/16'];
  const dns = asArray<string>(asObj(p.dhcpOptions).dnsServers);
  const tfName = sanitizeName(r.name);
  const dnsLine = dns.length ? `\n  dns_servers         = [${dns.map(quote).join(', ')}]` : '';
  const hcl = `resource "azurerm_virtual_network" "${tfName}" {
  name                = ${quote(r.name)}
  resource_group_name = azurerm_resource_group.${sanitizeName(r.resourceGroup)}.name
  location            = ${quote(r.location)}
  address_space       = [${prefixes.map(quote).join(', ')}]${dnsLine}${tagsBlock(r)}
}`;
  void ctx;
  return { hcl, tfType: 'azurerm_virtual_network', tfName };
}

function renderSubnet(r: ArgResource, ctx: RenderContext): RenderResult {
  const p = asObj(r.properties);
  const prefixes =
    asArray<string>(p.addressPrefixes).length > 0
      ? asArray<string>(p.addressPrefixes)
      : typeof p.addressPrefix === 'string'
        ? [p.addressPrefix]
        : [];
  const leaf = r.name.split('/').pop() ?? r.name;
  const tfName = sanitizeName(leaf);
  const vnetId = r.id.replace(/\/subnets\/[^/]+$/i, '');
  const vnetRef = ctx.idMap.get(vnetId.toLowerCase());
  const vnetLine = vnetRef
    ? `${vnetRef}.name`
    : quote((vnetId.split('/').pop() ?? '<vnet>') as string);
  const hcl = `resource "azurerm_subnet" "${tfName}" {
  name                 = ${quote(leaf)}
  resource_group_name  = azurerm_resource_group.${sanitizeName(r.resourceGroup)}.name
  virtual_network_name = ${vnetLine}
  address_prefixes     = [${prefixes.map(quote).join(', ')}]
}`;
  return { hcl, tfType: 'azurerm_subnet', tfName };
}

function renderNic(r: ArgResource, ctx: RenderContext): RenderResult {
  const p = asObj(r.properties);
  const ipcs = asArray<Record<string, unknown>>(p.ipConfigurations).map((ipc, i) => {
    const ipcProps = asObj(ipc.properties);
    const subnetId = (asObj(ipcProps.subnet).id as string | undefined) ?? undefined;
    const pipId = (asObj(ipcProps.publicIPAddress).id as string | undefined) ?? undefined;
    const alloc = ipcProps.privateIPAllocationMethod ?? 'Dynamic';
    const pipLine = pipId ? `\n    public_ip_address_id          = ${refOrLiteral(pipId, ctx)}` : '';
    return `  ip_configuration {
    name                          = ${quote((ipc.name as string) ?? `ipconfig${i + 1}`)}
    subnet_id                     = ${subnetId ? refOrLiteral(subnetId, ctx) : '"<TODO: subnet id>"'}
    private_ip_address_allocation = ${quote(alloc)}${pipLine}
  }`;
  });
  const tfName = sanitizeName(r.name);
  const hcl = `resource "azurerm_network_interface" "${tfName}" {
  name                = ${quote(r.name)}
  resource_group_name = azurerm_resource_group.${sanitizeName(r.resourceGroup)}.name
  location            = ${quote(r.location)}

${ipcs.join('\n\n')}${tagsBlock(r)}
}`;
  return { hcl, tfType: 'azurerm_network_interface', tfName };
}

function renderNsg(r: ArgResource): RenderResult {
  const p = asObj(r.properties);
  const rules = asArray<Record<string, unknown>>(p.securityRules).map((rule) => {
    const rp = asObj(rule.properties);
    const lines = [
      `    name                       = ${quote(rule.name as string)}`,
      `    priority                   = ${rp.priority}`,
      `    direction                  = ${quote(rp.direction)}`,
      `    access                     = ${quote(rp.access)}`,
      `    protocol                   = ${quote(rp.protocol)}`,
      `    source_port_range          = ${quote(rp.sourcePortRange ?? '*')}`,
      `    destination_port_range     = ${quote(rp.destinationPortRange ?? '*')}`,
      `    source_address_prefix      = ${quote(rp.sourceAddressPrefix ?? '*')}`,
      `    destination_address_prefix = ${quote(rp.destinationAddressPrefix ?? '*')}`,
    ];
    return `  security_rule {\n${lines.join('\n')}\n  }`;
  });
  const tfName = sanitizeName(r.name);
  const hcl = `resource "azurerm_network_security_group" "${tfName}" {
  name                = ${quote(r.name)}
  resource_group_name = azurerm_resource_group.${sanitizeName(r.resourceGroup)}.name
  location            = ${quote(r.location)}

${rules.join('\n\n')}${tagsBlock(r)}
}`;
  return { hcl, tfType: 'azurerm_network_security_group', tfName };
}

function renderPublicIp(r: ArgResource): RenderResult {
  const p = (r.properties ?? {}) as Record<string, unknown>;
  const tfName = sanitizeName(r.name);
  const hcl = `resource "azurerm_public_ip" "${tfName}" {
  name                = ${quote(r.name)}
  resource_group_name = azurerm_resource_group.${sanitizeName(r.resourceGroup)}.name
  location            = ${quote(r.location)}
  allocation_method   = ${quote(p.publicIPAllocationMethod ?? 'Static')}
  sku                 = ${quote(r.sku?.name ?? 'Standard')}${tagsBlock(r)}
}`;
  return { hcl, tfType: 'azurerm_public_ip', tfName };
}

function renderRouteTable(r: ArgResource): RenderResult {
  const tfName = sanitizeName(r.name);
  const hcl = `resource "azurerm_route_table" "${tfName}" {
  name                = ${quote(r.name)}
  resource_group_name = azurerm_resource_group.${sanitizeName(r.resourceGroup)}.name
  location            = ${quote(r.location)}${tagsBlock(r)}
}`;
  return { hcl, tfType: 'azurerm_route_table', tfName };
}

function renderManagedDisk(r: ArgResource): RenderResult {
  const p = (r.properties ?? {}) as Record<string, unknown>;
  const tfName = sanitizeName(r.name);
  const createOption = ((p.creationData as { createOption?: string })?.createOption) ?? 'Empty';
  const hcl = `resource "azurerm_managed_disk" "${tfName}" {
  name                 = ${quote(r.name)}
  resource_group_name  = azurerm_resource_group.${sanitizeName(r.resourceGroup)}.name
  location             = ${quote(r.location)}
  storage_account_type = ${quote(r.sku?.name ?? 'Standard_LRS')}
  create_option        = ${quote(createOption)}
  disk_size_gb         = ${(p.diskSizeGB as number) ?? 128}${tagsBlock(r)}
}`;
  return { hcl, tfType: 'azurerm_managed_disk', tfName };
}

function renderVm(r: ArgResource, ctx: RenderContext): RenderResult {
  const p = asObj(r.properties);
  const osProfile = asObj(p.osProfile);
  const isWindows = Boolean(osProfile.windowsConfiguration);
  const tfType = isWindows ? 'azurerm_windows_virtual_machine' : 'azurerm_linux_virtual_machine';
  const tfName = sanitizeName(r.name);
  const hwProfile = asObj(p.hardwareProfile);
  const networkProfile = asObj(p.networkProfile);
  const nics = asArray<{ id?: string }>(networkProfile.networkInterfaces)
    .map((n) => (n.id ? refOrLiteral(n.id, ctx) : '"<TODO: nic id>"'))
    .join(', ');
  const storageProfile = asObj(p.storageProfile);
  const imageRef = asObj(storageProfile.imageReference);
  const osDisk = asObj(storageProfile.osDisk);
  const sourceImageBlock = imageRef.publisher
    ? `\n  source_image_reference {
    publisher = ${quote(imageRef.publisher)}
    offer     = ${quote(imageRef.offer)}
    sku       = ${quote(imageRef.sku)}
    version   = ${quote(imageRef.version ?? 'latest')}
  }`
    : '';
  const credBlock = isWindows
    ? `\n  admin_password = var.admin_password`
    : `\n  admin_ssh_key {
    username   = var.admin_username
    public_key = var.admin_ssh_public_key
  }`;
  const hcl = `resource "${tfType}" "${tfName}" {
  name                  = ${quote(r.name)}
  resource_group_name   = azurerm_resource_group.${sanitizeName(r.resourceGroup)}.name
  location              = ${quote(r.location)}
  size                  = ${quote(hwProfile.vmSize ?? 'Standard_B2s')}
  admin_username        = ${quote(osProfile.adminUsername ?? 'azureuser')}
  network_interface_ids = [${nics}]

  os_disk {
    name                 = ${quote(osDisk.name ?? `${r.name}-osdisk`)}
    caching              = ${quote(osDisk.caching ?? 'ReadWrite')}
    storage_account_type = ${quote(asObj(osDisk.managedDisk).storageAccountType ?? 'StandardSSD_LRS')}
  }${sourceImageBlock}
  # ⚠ password / SSH key NOT exported — set via terraform.tfvars before apply.${credBlock}${tagsBlock(r)}
}`;
  return { hcl, tfType, tfName };
}

function renderKeyVault(r: ArgResource): RenderResult {
  const p = (r.properties ?? {}) as Record<string, unknown>;
  const tfName = sanitizeName(r.name);
  const hcl = `resource "azurerm_key_vault" "${tfName}" {
  name                          = ${quote(r.name)}
  resource_group_name           = azurerm_resource_group.${sanitizeName(r.resourceGroup)}.name
  location                      = ${quote(r.location)}
  tenant_id                     = ${quote(p.tenantId ?? '<tenant-id>')}
  sku_name                      = ${quote(((p.sku as { name?: string })?.name) ?? 'standard')}
  enabled_for_disk_encryption   = ${p.enabledForDiskEncryption === true ? 'true' : 'false'}
  enable_rbac_authorization     = ${p.enableRbacAuthorization === true ? 'true' : 'false'}
  public_network_access_enabled = ${p.publicNetworkAccess === 'Disabled' ? 'false' : 'true'}
  soft_delete_retention_days    = ${(p.softDeleteRetentionInDays as number) ?? 7}
  purge_protection_enabled      = ${p.enablePurgeProtection === true ? 'true' : 'false'}${tagsBlock(r)}
}`;
  return { hcl, tfType: 'azurerm_key_vault', tfName };
}

function renderServicePlan(r: ArgResource): RenderResult {
  const p = (r.properties ?? {}) as Record<string, unknown>;
  const tfName = sanitizeName(r.name);
  const osKind = (p.kind as string)?.toLowerCase() === 'windows' ? 'Windows' : 'Linux';
  const hcl = `resource "azurerm_service_plan" "${tfName}" {
  name                = ${quote(r.name)}
  resource_group_name = azurerm_resource_group.${sanitizeName(r.resourceGroup)}.name
  location            = ${quote(r.location)}
  os_type             = ${quote(osKind)}
  sku_name            = ${quote(r.sku?.name ?? 'B1')}${tagsBlock(r)}
}`;
  return { hcl, tfType: 'azurerm_service_plan', tfName };
}

function renderWebApp(r: ArgResource, ctx: RenderContext): RenderResult {
  const p = (r.properties ?? {}) as Record<string, unknown>;
  const kind = (r.kind ?? '').toLowerCase();
  const isWindows = kind.includes('app') && !kind.includes('linux');
  const tfType = isWindows ? 'azurerm_windows_web_app' : 'azurerm_linux_web_app';
  const tfName = sanitizeName(r.name);
  const planId = p.serverFarmId as string | undefined;
  const planRef = planId ? refOrLiteral(planId, ctx) : '"<TODO: serverFarmId>"';
  const hcl = `resource "${tfType}" "${tfName}" {
  name                = ${quote(r.name)}
  resource_group_name = azurerm_resource_group.${sanitizeName(r.resourceGroup)}.name
  location            = ${quote(r.location)}
  service_plan_id     = ${planRef}

  site_config {
    always_on = ${p.alwaysOn === false ? 'false' : 'true'}
  }${tagsBlock(r)}
}`;
  return { hcl, tfType, tfName };
}

function renderLogAnalytics(r: ArgResource): RenderResult {
  const p = (r.properties ?? {}) as Record<string, unknown>;
  const tfName = sanitizeName(r.name);
  const retention = (p.retentionInDays as number) ?? 30;
  const hcl = `resource "azurerm_log_analytics_workspace" "${tfName}" {
  name                = ${quote(r.name)}
  resource_group_name = azurerm_resource_group.${sanitizeName(r.resourceGroup)}.name
  location            = ${quote(r.location)}
  sku                 = ${quote(((p.sku as { name?: string })?.name) ?? 'PerGB2018')}
  retention_in_days   = ${retention}${tagsBlock(r)}
}`;
  return { hcl, tfType: 'azurerm_log_analytics_workspace', tfName };
}

function renderAppInsights(r: ArgResource, ctx: RenderContext): RenderResult {
  const p = (r.properties ?? {}) as Record<string, unknown>;
  const tfName = sanitizeName(r.name);
  const workspaceId = p.WorkspaceResourceId as string | undefined;
  const wsLine = workspaceId
    ? `\n  workspace_id        = ${refOrLiteral(workspaceId, ctx)}`
    : '';
  const hcl = `resource "azurerm_application_insights" "${tfName}" {
  name                = ${quote(r.name)}
  resource_group_name = azurerm_resource_group.${sanitizeName(r.resourceGroup)}.name
  location            = ${quote(r.location)}
  application_type    = ${quote(p.Application_Type ?? 'web')}${wsLine}${tagsBlock(r)}
}`;
  return { hcl, tfType: 'azurerm_application_insights', tfName };
}

// ────────────────────────────────────────────────────────────────────────────
// Dispatch
// ────────────────────────────────────────────────────────────────────────────

const RENDERERS: Record<string, (r: ArgResource, ctx: RenderContext) => RenderResult> = {
  'microsoft.storage/storageaccounts': renderStorageAccount,
  'microsoft.network/virtualnetworks': renderVirtualNetwork,
  'microsoft.network/virtualnetworks/subnets': renderSubnet,
  'microsoft.network/networkinterfaces': renderNic,
  'microsoft.network/networksecuritygroups': renderNsg,
  'microsoft.network/publicipaddresses': renderPublicIp,
  'microsoft.network/routetables': renderRouteTable,
  'microsoft.compute/virtualmachines': renderVm,
  'microsoft.compute/disks': renderManagedDisk,
  'microsoft.keyvault/vaults': renderKeyVault,
  'microsoft.web/serverfarms': renderServicePlan,
  'microsoft.web/sites': renderWebApp,
  'microsoft.operationalinsights/workspaces': renderLogAnalytics,
  'microsoft.insights/components': renderAppInsights,
};

function renderResource(r: ArgResource, ctx: RenderContext): RenderResult {
  const fn = RENDERERS[r.type.toLowerCase()];
  if (!fn) {
    return {
      hcl: `# ─ Unsupported type: ${r.type}
# Resource name: ${r.name}
# Resource id:   ${r.id}
#
# This resource type does not have a dedicated renderer in the web preview.
# Run the PowerShell module locally for the aztfexport-backed translation:
#   Import-Module AzureEstateExporter
#   Export-AzureEstate -SubscriptionId ${r.subscriptionId} -ResourceGroup ${r.resourceGroup}`,
    };
  }
  // Failure-tolerant: a single mis-shaped resource never breaks the whole repo.
  try {
    return fn(r, ctx);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    return {
      hcl: `# ─ Renderer error on ${r.type} (${r.name})
# ${msg}
# Resource id: ${r.id}
#
# Run the PowerShell module for the production-grade translation.`,
    };
  }
}

// ────────────────────────────────────────────────────────────────────────────
// Entry point
// ────────────────────────────────────────────────────────────────────────────

export function generateTerraformRepo(opts: GenerateOptions): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const version = opts.generatorVersion ?? 'web-preview';

  // Group by RG.
  const byRg = new Map<string, ArgResource[]>();
  for (const r of opts.resources) {
    const arr = byRg.get(r.resourceGroup) ?? [];
    arr.push(r);
    byRg.set(r.resourceGroup, arr);
  }

  const supportedTypes = new Set(Object.keys(RENDERERS));
  const supportedCount = opts.resources.filter((r) => supportedTypes.has(r.type.toLowerCase())).length;
  const totalCount = opts.resources.length;
  const skippedTypes = new Set(
    opts.resources.filter((r) => !supportedTypes.has(r.type.toLowerCase())).map((r) => r.type),
  );

  // Per-RG files.
  for (const [rgName, rgResources] of byRg) {
    const ctx: RenderContext = { idMap: buildIdMap(rgResources), resource: rgResources[0] };
    const rgLocation = rgResources[0]?.location ?? 'westeurope';
    const blocks: string[] = [];

    blocks.push(renderResourceGroup(rgName, rgLocation, undefined));

    // Iterate in stable order: type then name.
    const sorted = [...rgResources].sort((a, b) =>
      a.type.localeCompare(b.type) || a.name.localeCompare(b.name),
    );
    const outputs: Array<{ tfType: string; tfName: string; azureName: string }> = [];
    for (const r of sorted) {
      const res = renderResource(r, { ...ctx, resource: r });
      if (res.hcl) blocks.push(res.hcl);
      if (res.tfType && res.tfName) {
        outputs.push({ tfType: res.tfType, tfName: res.tfName, azureName: r.name });
      }
    }

    const folder = `infra/${rgName}`;
    files.push({
      path: `${folder}/main.tf`,
      content: HEADER_NOTICE + '\n' + blocks.join('\n\n') + '\n',
      language: 'hcl',
    });

    files.push({
      path: `${folder}/provider.tf`,
      content: `terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
  }
}

provider "azurerm" {
  features {}
  subscription_id = var.subscription_id
}
`,
      language: 'hcl',
    });

    files.push({
      path: `${folder}/variables.tf`,
      content: `variable "subscription_id" {
  description = "Target Azure subscription ID."
  type        = string
}

variable "admin_username" {
  description = "Default admin username for Linux VMs (override per-VM as needed)."
  type        = string
  default     = "azureuser"
}

variable "admin_ssh_public_key" {
  description = "SSH public key body (single line) for Linux VMs."
  type        = string
  default     = ""
}

variable "admin_password" {
  description = "Admin password for Windows VMs. NEVER commit this; use TF_VAR_admin_password."
  type        = string
  sensitive   = true
  default     = ""
}
`,
      language: 'hcl',
    });

    files.push({
      path: `${folder}/terraform.tfvars.example`,
      content: `# Copy this file to terraform.tfvars (gitignored) and fill in your values.
subscription_id      = ${quote(opts.subscriptionId)}
admin_username       = "azureuser"
admin_ssh_public_key = "ssh-ed25519 AAAA..."
# admin_password set via env: $env:TF_VAR_admin_password = '<secret>'
`,
      language: 'hcl',
    });

    // outputs.tf — IDs of every supported resource.
    const outputsHcl = outputs
      .map(
        (o) => `output "${sanitizeName(o.azureName)}_id" {
  description = "Azure ID for ${o.azureName} (${o.tfType})."
  value       = ${o.tfType}.${o.tfName}.id
}`,
      )
      .join('\n\n');
    if (outputsHcl) {
      files.push({
        path: `${folder}/outputs.tf`,
        content:
          `# Per-resource outputs so other Terraform repos can consume these IDs.\n\n` +
          outputsHcl +
          '\n',
        language: 'hcl',
      });
    }

    // Per-RG README.
    files.push({
      path: `${folder}/README.md`,
      content: `# \`${rgName}\`

Generated by azure-estate-exporter (web preview, ${version}).

- Source subscription: \`${opts.subscriptionId}\`
- Resources rendered: ${rgResources.length}
- Of which fully supported: ${
        rgResources.filter((r) => supportedTypes.has(r.type.toLowerCase())).length
      }

## Quick start

\`\`\`powershell
Copy-Item terraform.tfvars.example terraform.tfvars
# edit subscription_id and any admin_* variables

terraform init
terraform plan
\`\`\`

> **⚠ Preview**: this folder was generated client-side and does NOT import
> resources into state. The first \`terraform plan\` will likely show
> "create" actions for everything. To get a true "No changes" plan against
> the existing estate, run the PowerShell module:
>
> \`\`\`powershell
> Import-Module AzureEstateExporter
> Export-AzureEstate -SubscriptionId ${opts.subscriptionId} -ResourceGroup ${rgName}
> \`\`\`
>
> That produces a \`terraform-repo/infra/${rgName}/\` folder with a
> \`bootstrap-import.ps1\` that imports every resource into state.
`,
      language: 'markdown',
    });
  }

  // Root files.
  files.push({
    path: 'README.md',
    content: `# Terraform baseline (web preview) — ${opts.subscriptionName ?? opts.subscriptionId}

Generated in the browser by **azure-estate-exporter** (${version}).

## Contents

| Resource group | Resources |
|----------------|----------:|
${[...byRg.entries()]
  .map(([rg, rs]) => `| \`${rg}\` | ${rs.length} |`)
  .join('\n')}

- **${supportedCount}** of **${totalCount}** resources rendered with native HCL.
${
  skippedTypes.size
    ? `- **${skippedTypes.size}** resource type(s) emitted as commented stubs (use the PowerShell module for a full translation):\n${
        [...skippedTypes].map((t) => `  - \`${t}\``).join('\n')
      }`
    : ''
}

## ⚠ This is a baseline, NOT a perfect clone

The web preview is fast and visual but the **PowerShell module + aztfexport**
remain the production path:

\`\`\`powershell
Import-Module AzureEstateExporter
Export-AzureEstate -SubscriptionId ${opts.subscriptionId}
# -> out/<timestamp>/terraform-repo/  (with bootstrap-import.ps1)
\`\`\`

The PowerShell flow imports every resource into Terraform state, so the
first \`terraform plan\` against the existing estate shows **No changes**.

## What is NOT covered

- Secrets, data-plane contents, key material.
- VM passwords / SSH keys — must be supplied via \`terraform.tfvars\`.
- Cross-RG references that point outside the selected scope.
- Resource types not in the in-browser renderer set (see commented stubs in
  the \`main.tf\` files).

## Layout

\`\`\`
.
├── README.md                # this file
├── .gitignore               # standard Terraform .gitignore
├── backend.tf.example       # Azure Storage backend stub
└── infra/
    └── <rg>/
        ├── main.tf
        ├── provider.tf
        ├── variables.tf
        ├── terraform.tfvars.example
        ├── outputs.tf
        └── README.md
\`\`\`
`,
    language: 'markdown',
  });

  files.push({
    path: '.gitignore',
    content: `# Local state (do not commit)
*.tfstate
*.tfstate.*
*.tfstate.backup
.terraform/
crash.log
crash.*.log

# Variable files with secrets — keep .example files committed
*.tfvars
!*.tfvars.example

# OS / editor noise
.DS_Store
Thumbs.db
.vscode/
.idea/
`,
    language: 'text',
  });

  files.push({
    path: 'backend.tf.example',
    content: `# Drop your remote backend here. Example for Azure Storage:
#
# terraform {
#   backend "azurerm" {
#     resource_group_name  = "rg-tfstate"
#     storage_account_name = "sttfstate0001"
#     container_name       = "tfstate"
#     key                  = "azure-estate-exporter/<rg-name>.tfstate"
#   }
# }
#
# Copy this file to each infra/<rg>/ folder as backend.tf and run
# terraform init -migrate-state.
`,
    language: 'hcl',
  });

  return files;
}

/** Quick lookup so the UI can show "X% of resources fully supported". */
export function isFullySupported(armType: string): boolean {
  return Object.prototype.hasOwnProperty.call(RENDERERS, armType.toLowerCase());
}
